[project]
name = 'Time-Loop-Management-System'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.causal-loop-identification]
path = 'contracts/causal-loop-identification.clar'
clarity_version = 2
epoch = 2.5

[contracts.historical-integrity]
path = 'contracts/historical-integrity.clar'
clarity_version = 2
epoch = 2.5

[contracts.temporal-energy-recycling]
path = 'contracts/temporal-energy-recycling.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
